routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('posts','PostsController');
Route::resource('comments','CommentController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/ajax_add_comment/{id}/{comment}/{parentid?}', 'CommentController@ajax_add_comment');

app/Comment.php
<?php
  
namespace App;
  
use Illuminate\Database\Eloquent\Model;
  
class Comment extends Model
{
    
   
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['user_id', 'post_id', 'parent_id', 'body'];
    protected $table = "comment";
    
   
    /**
     * The belongs to Relationship
     *
     * @var array
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
   
    /**
     * The has Many Relationship
     *
     * @var array
     */
    public function replies()
    {
        return $this->hasMany(Comment::class, 'parent_id');
    }
}

app/Post.php
<?php
  
namespace App;
  
use Illuminate\Database\Eloquent\Model;
  
class Post extends Model
{
    
  
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'content', 'image'];
    protected $table = "post";

   
    /**
     * The has Many Relationship
     *
     * @var array
     */
    public function comments()
    {
        return $this->hasMany(Comment::class)->whereNull('parent_id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CommentController.php
<?php
   
namespace App\Http\Controllers;
   
use Illuminate\Http\Request;
use App\Comment;
use App\Post;

   
class CommentController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'body'=>'required',
        ]);
   
        $input = $request->all();
        $input['user_id'] = auth()->user()->id;
    
        Comment::create($input);
   
        return back();
    }

    public function ajax_add_comment($post_id, $comment,$parent_id = NULL) {
        $input['body'] = $comment;
        $input['post_id'] = $post_id;        
        $input['user_id'] = auth()->user()->id;
        $input['parent_id'] = $parent_id;
    
        Comment::create($input);
        $post = Post::find($post_id);
        $comments = $post->comments;
        
        return view('posts.comments', compact('comments', 'post_id'))->render();        
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;


class PostsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function index()
    {
        $posts = Post::all();
    
        return view('posts.index', compact('posts'));
    }
   
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title'=>'required',
            'content'=>'required',
            'image'=>'required|mimes:jpg,png,jpeg'
        ]);

        $file = $request->file('image');        
        $imagename = $file->getClientOriginalName();
        $file->getClientOriginalExtension();         
        $destinationPath = public_path('uploads');
        
        $file->move($destinationPath,$file->getClientOriginalName());      
        
        $addPost = new Post;
        $addPost->title = $request->title;
        $addPost->content = $request->content;
        $addPost->image = $imagename;
        $addPost->save();

    
        return redirect()->route('posts.index');
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);
        return view('posts.show', compact('post'));
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('public/js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('public/css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/posts/comments.blade.php
@foreach($comments as $comment)
    <div class="display-comment" @if($comment->parent_id != null) style="margin-left:40px;" @endif>
        <strong>{{ $comment->user->name }}</strong>
        <p>{{ $comment->body }}</p>
        
        <form method="post" action="{{ route('comments.store') }}">
            @csrf
            <div class="form-group">
                <input type="text" name="body" class="form-control" id="body1_{{ $comment->id }}" />
                <div id="error_{{ $comment->id }}"></div>
                <input type="hidden" name="post_id" value="{{ $post_id }}" id="post_id1" />
                <input type="hidden" name="parent_id" value="{{ $comment->id }}" id="parent_id1" />
            </div>
            <div class="form-group">
                <a href="javascript:void(0);" onclick="addReply('{{ $comment->id }}')" class="btn btn-info">Reply</a>
            </div>
        </form>
        @include('posts.comments', ['comments' => $comment->replies])
    </div>
@endforeach

resources/views/posts/create.blade.php
@extends('layouts.app')
   
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create Post</div>
                <div class="card-body">
                    {!! Form::open(['method' => 'POST', 'route' => ['posts.store'], 'files' => true,]) !!}
                        <div class="form-group">
                            @csrf
                            <label class="label">Title: </label>
                            {!! Form::text('title', null, ['class' => 'form-control', 'required' => 'required']) !!}

                        </div>
                        <div class="form-group">
                            <label class="label">Post Content: </label>
                            {!! Form::textarea('content', null, ['class' => 'form-control', 'required' => 'required']) !!}
                        </div>
                        <div class="form-group">
                            <label class="label">Image: </label>
                            {!! Form::file('image', ['class' => 'form-control', 'required' => 'required', 'accept'=>"image/*"]) !!}

                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-success" />
                        
                            <a href="{{url('posts')}}"  class="btn btn-info" >Back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')
   
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <h1>Manage Posts</h1>
            <a href="{{ route('posts.create') }}" class="btn btn-success" style="float: right">Create Post</a>
            <table class="table table-bordered">
                <thead>
                    <th width="80px">Id</th>
                    <th>Title</th>
                    <th width="150px">Action</th>
                </thead>
                <tbody>
                @foreach($posts as $post)
                <tr>
                    <td>{{ $post->id }}</td>
                    <td>{{ $post->title }}</td>
                    <td>
                        <a href="{{ route('posts.show', $post->id) }}" class="btn ">View Post</a>
                    </td>
                </tr>
                @endforeach
                </tbody>
   
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')
   
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">                    
                    <br/>
                    <h2>{{ $post->title }}</h2>
                    <p>
                        {{ $post->content }}
                    </p>
                    <p>
                        <img src="{{ url('public/uploads/'.$post->image) }}" height="50px" width="50px" >
                    </p>
                    <hr />
                    <h4>Comments</h4>
                    
                    <div id="replace_div">
                    @include('posts.comments', ['comments' => $post->comments, 'post_id' => $post->id])
                    </div>
                    <hr />
                    <h4>Add comment</h4>
                    <form method="post" action="{{ route('comments.store'   ) }}" id="xyz">
                        @csrf
                        <div class="form-group">
                            <textarea class="form-control" name="body" id="body"></textarea>
                            <div id="error"></div>

                            <input type="hidden" name="post_id" value="{{ $post->id }}" id="post_id" />
                        </div>
                        <div class="form-group">
                            <input type="button" onclick="addComment();" class="btn btn-success" value="Add Comment" />
                        </div>
                    </form>
   
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
<script type="text/javascript" src="{{url('/public/js/jquery.min.js')}}"></script>
<script>

  $(document).ready(function(){
    
});
  function addComment() {
    var post_id = $("#post_id").val();
    var body = $("#body").val();
    
    console.log(post_id);
    console.log(body);
    if(body == '') {
        $("#error").html('Enter your comment');
        return false;
    }
    $.ajax({
        url : "{{url('/')}}"+ '/ajax_add_comment/'+post_id+'/'+body,
        type: "GET",
        success: function(data)
        {
            $("#xyz").closest('form').find("input[type=text], textarea").val("");            
            $("#replace_div").empty().html(data);            
        }
    });
    }

    function addReply(parent_id) {
    var post_id = $("#post_id1").val();
    var body = $("#body1_"+parent_id).val();
    // alert(parent_id);
    if(parent_id == undefined) {
        parent_id = '';
    }
    console.log(post_id);
    console.log(body);
    console.log(parent_id);
    if(body == '') {
        $("#error_"+parent_id).html('Enter your comment');
        return false;
    }

    $.ajax({
        url : "{{url('/')}}"+ '/ajax_add_comment/'+post_id+'/'+body+'/'+parent_id,
        type: "GET",
        success: function(data)
        {
            $(this).closest('form').find("input[type=text], textarea").val("");            
            $("#replace_div").empty().html(data);
            
        }
    });
    }
</script>